import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Suspense } from 'react';
import Head from 'next/head';

const roboto = Roboto({
    subsets: ['latin'],
    weight: ['100', '300', '400', '500', '700', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <Head>
                <meta
                    http-equiv='Content-Security-Policy'
                    content='upgrade-insecure-requests'
                ></meta>
            </Head>
            <body className={`${roboto.className}`}>
                <Suspense>{children}</Suspense>
            </body>
        </html>
    );
}
